name = "cfmail"
main = "src/worker.ts"
compatibility_date = "2026-02-17"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "CFMAILDB"

[[r2_buckets]]
binding = "MAIL_RAW"

[vars]
APP_NAME = "个人邮箱"

# Secrets (set by wrangler secret put):
# RESEND_API_KEY
# RESEND_FROM
# JWT_SECRET
