name = "cfemail"
main = "src/worker.ts"
compatibility_date = "2026-02-17"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"


[vars]
APP_NAME  = "个人邮箱"
# RESEND_API_KEY
# RESEND_FROM
# JWT_SECRET
