name = "cfemail"
main = "src/worker.ts"
compatibility_date = "2026-02-17"
workers_dev = true
keep_vars = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "CFMAILDB"
database_name = "cfemail-db"

[[r2_buckets]]
binding = "MAIL_RAW"
bucket_name = "cfemail-raw"



[vars]
APP_NAME  = "个人邮箱"
# RESEND_API_KEY
# RESEND_FROM
# JWT_SECRET

